apiVersion: v1
kind: ReplicationController
metadata:
  name: bookshelf-app
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: bookshelf
        tier: backend
    spec:
      containers:
        - name: bookshelf-app
          image: gcr.io/bookshelf-238313/bookshelf
          imagePullPolicy: Always
          env:
            - name: PROCESSES
              value: bookshelf
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: bookshelf-app
  labels:
    app: bookshelf
    tier: backend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: bookshelf
    tier: backend